# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 19:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512, verbose_name='title')),
                ('brief', models.TextField(blank=True, verbose_name='brief')),
                ('author', models.CharField(blank=True, max_length=512, verbose_name='author')),
                ('link', models.URLField(blank=True, verbose_name='link')),
                ('duration', models.DurationField(verbose_name='duration')),
                ('num_people', models.PositiveSmallIntegerField(verbose_name='number of people')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
            ],
            options={
                'verbose_name_plural': 'Activities',
                'verbose_name': 'Activity',
            },
        ),
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('requested', models.DateTimeField(auto_now_add=True, verbose_name='created on')),
                ('published', models.DateTimeField(blank=True, null=True, verbose_name='published on')),
                ('approved', models.BooleanField(default=False, verbose_name='is approved')),
                ('comment', models.TextField(null=True, verbose_name='comment')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='contact email')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name_plural': 'Approvals',
                'verbose_name': 'Approval',
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name='izena')),
            ],
            options={
                'verbose_name_plural': 'Goals',
                'verbose_name': 'Goal',
            },
        ),
        migrations.CreateModel(
            name='GroupFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name='izena')),
            ],
            options={
                'verbose_name_plural': 'Group features',
                'verbose_name': 'Group feature',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name='izena')),
            ],
            options={
                'verbose_name_plural': 'Language',
                'verbose_name': 'Language',
            },
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512, verbose_name='title')),
                ('brief', models.TextField(blank=True, verbose_name='brief')),
                ('author', models.CharField(blank=True, max_length=512, verbose_name='author')),
                ('link', models.URLField(blank=True, verbose_name='link')),
                ('pages', models.PositiveIntegerField(verbose_name='pages')),
                ('year', models.PositiveIntegerField(verbose_name='year')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material.Language', verbose_name='language')),
            ],
            options={
                'verbose_name_plural': 'Reading',
                'verbose_name': 'Reading',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name='izena')),
            ],
            options={
                'verbose_name_plural': 'Subjects',
                'verbose_name': 'Subject',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512, verbose_name='title')),
                ('brief', models.TextField(blank=True, verbose_name='brief')),
                ('author', models.CharField(blank=True, max_length=512, verbose_name='author')),
                ('link', models.URLField(blank=True, verbose_name='link')),
                ('duration', models.DurationField(verbose_name='duration')),
                ('year', models.PositiveIntegerField(verbose_name='year')),
                ('audios', models.ManyToManyField(blank=True, related_name='video_audio', to='material.Language', verbose_name='audio languages')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material.Subject', verbose_name='subject')),
                ('subtitles', models.ManyToManyField(blank=True, related_name='video_subtitle', to='material.Language', verbose_name='subtitle languages')),
            ],
            options={
                'verbose_name_plural': 'Videos',
                'verbose_name': 'Video',
            },
        ),
        migrations.AddField(
            model_name='reading',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material.Subject', verbose_name='subject'),
        ),
        migrations.AddField(
            model_name='activity',
            name='goal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material.Goal', verbose_name='goal'),
        ),
        migrations.AddField(
            model_name='activity',
            name='group_feature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='material.GroupFeature', verbose_name='group feature'),
        ),
        migrations.AddField(
            model_name='activity',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='material.Subject', verbose_name='subject'),
        ),
        migrations.AlterUniqueTogether(
            name='approval',
            unique_together=set([('content_type', 'object_id')]),
        ),
    ]
