# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-08 04:37
from __future__ import unicode_literals

from django.db import migrations, models
import tk.material.models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reading',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[tk.material.models.validate_year], verbose_name='year'),
        ),
    ]
