# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-05 15:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approval',
            name='published',
        ),
    ]
