# Generated by Django 2.0 on 2018-07-03 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reading',
            name='attachment',
        ),
        migrations.RemoveField(
            model_name='video',
            name='attachment',
        ),
        migrations.AlterField(
            model_name='reading',
            name='url',
            field=models.URLField(blank=True, help_text='Link to the reading.', verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.URLField(blank=True, help_text='Link to the video.', verbose_name='URL'),
        ),
    ]
