# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 19:55
from __future__ import unicode_literals

from django.db import migrations
import localized_fields.fields.field


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='approval',
            options={'ordering': ['-requested'], 'verbose_name': 'Approval', 'verbose_name_plural': 'Approvals'},
        ),
        migrations.AlterModelOptions(
            name='goal',
            options={'ordering': ['name'], 'verbose_name': 'Goal', 'verbose_name_plural': 'Goals'},
        ),
        migrations.AlterModelOptions(
            name='groupfeature',
            options={'ordering': ['name'], 'verbose_name': 'Group feature', 'verbose_name_plural': 'Group features'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['name'], 'verbose_name': 'Location', 'verbose_name_plural': 'Locations'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['name'], 'verbose_name': 'Subject', 'verbose_name_plural': 'Subjects'},
        ),
        migrations.AlterField(
            model_name='goal',
            name='name',
            field=localized_fields.fields.field.LocalizedField(max_length=512, required=[], uniqueness=[], verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='groupfeature',
            name='name',
            field=localized_fields.fields.field.LocalizedField(max_length=512, required=[], uniqueness=[], verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=localized_fields.fields.field.LocalizedField(max_length=512, required=[], uniqueness=[], verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=localized_fields.fields.field.LocalizedField(max_length=512, required=[], uniqueness=[], verbose_name='name'),
        ),
    ]
