# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 09:36
from __future__ import unicode_literals

from django.db import migrations, models
import tk.material.models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0002_auto_20170504_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reading',
            name='year',
            field=models.PositiveIntegerField(validators=[tk.material.models.validate_year], verbose_name='year'),
        ),
        migrations.AlterField(
            model_name='video',
            name='year',
            field=models.PositiveIntegerField(validators=[tk.material.models.validate_year], verbose_name='year'),
        ),
    ]
