# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-06 18:13
from __future__ import unicode_literals

from django.db import migrations, models
import tk.material.fields


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0002_remove_approval_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reading',
            name='language',
        ),
        migrations.AddField(
            model_name='reading',
            name='languages',
            field=tk.material.fields.LanguageField(base_field=models.CharField(max_length=7), default=['en'], size=None, verbose_name='languages'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='video',
            name='audios',
        ),
        migrations.AddField(
            model_name='video',
            name='audios',
            field=tk.material.fields.LanguageField(base_field=models.CharField(max_length=7), blank=True, default=[], size=None, verbose_name='audio languages'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='video',
            name='subtitles',
        ),
        migrations.AddField(
            model_name='video',
            name='subtitles',
            field=tk.material.fields.LanguageField(base_field=models.CharField(max_length=7), blank=True, default=[], size=None, verbose_name='subtitle languages'),
            preserve_default=False,
        ),
    ]
