# Generated by Django 2.1.4 on 2018-12-26 12:14

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('material', '0002_auto_20180703_1734'),
    ]

    operations = [
       migrations.RenameField('video', 'duration', 'old_duration'),
       migrations.RenameField('activity', 'duration', 'old_duration'),
       migrations.AddField(
           model_name='video',
           name='duration',
           field=models.PositiveSmallIntegerField(
               help_text='Duration in minutes.',
               verbose_name='duration',
               default=0),
           preserve_default=False,
       ),
       migrations.AddField(
           model_name='activity',
           name='duration',
           field=models.PositiveSmallIntegerField(
               null=True,
               blank=True,
               verbose_name='duration',
               help_text='Duration in minutes.'),
       ),
       migrations.RunSQL('update material_video set duration = extract(epoch from old_duration);'),
       migrations.RunSQL('update material_activity set duration = extract(epoch from old_duration);'),
       migrations.RemoveField('video', 'old_duration'),
       migrations.RemoveField('activity', 'old_duration'),
    ]
