# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 19:56
from __future__ import unicode_literals

from django.db import migrations
import localized_fields.fields.field


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0002_auto_20170704_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='notes',
            field=localized_fields.fields.field.LocalizedField(blank=True, null=True, required=[], uniqueness=[], verbose_name='notes'),
        ),
    ]
