# Generated by Django 2.1.4 on 2018-12-27 21:32

from django.db import migrations
import localized_fields.fields.char_field


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0003_auto_20181226_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupfeature',
            name='name',
            field=localized_fields.fields.char_field.LocalizedCharField(max_length=512, required=[], uniqueness=[], verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=localized_fields.fields.char_field.LocalizedCharField(max_length=512, required=[], uniqueness=[], verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=localized_fields.fields.char_field.LocalizedCharField(max_length=512, required=[], uniqueness=[], verbose_name='name'),
        ),
    ]
