# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0003_auto_20170504_1136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='goal',
        ),
        migrations.AddField(
            model_name='activity',
            name='goals',
            field=models.ManyToManyField(to='material.Goal', verbose_name='goals'),
        ),
    ]
