# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 18:18
from __future__ import unicode_literals

from django.db import migrations
import localized_fields.fields.char_field
import localized_fields.fields.text_field


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0003_auto_20170704_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='notes',
            field=localized_fields.fields.text_field.LocalizedTextField(blank=True, null=True, required=[], uniqueness=[], verbose_name='notes'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='name',
            field=localized_fields.fields.char_field.LocalizedCharField(max_length=512, required=[], uniqueness=[], verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='groupfeature',
            name='name',
            field=localized_fields.fields.char_field.LocalizedCharField(max_length=512, required=[], uniqueness=[], verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=localized_fields.fields.char_field.LocalizedCharField(max_length=512, required=[], uniqueness=[], verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='material',
            name='title',
            field=localized_fields.fields.char_field.LocalizedCharField(max_length=512, required=[], uniqueness=[], verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=localized_fields.fields.char_field.LocalizedCharField(max_length=512, required=[], uniqueness=[], verbose_name='name'),
        ),
    ]
