# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-06 18:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0003_auto_20170606_2013'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Language',
        ),
    ]
