# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-09 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0004_auto_20170705_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reading',
            name='pages',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='pages'),
        ),
        migrations.AlterField(
            model_name='video',
            name='duration',
            field=models.DurationField(blank=True, null=True, verbose_name='duration'),
        ),
    ]
