# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-06 21:07
from __future__ import unicode_literals

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0004_delete_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='brief',
            field=markdownx.models.MarkdownxField(blank=True, verbose_name='brief'),
        ),
        migrations.AlterField(
            model_name='material',
            name='brief_es',
            field=markdownx.models.MarkdownxField(blank=True, null=True, verbose_name='brief'),
        ),
        migrations.AlterField(
            model_name='material',
            name='brief_eu',
            field=markdownx.models.MarkdownxField(blank=True, null=True, verbose_name='brief'),
        ),
    ]
