# Generated by Django 2.1.4 on 2019-01-04 23:17

import django.contrib.postgres.fields.ranges
from django.db import migrations
from psycopg2.extras import NumericRange


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0004_auto_20181227_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='num_people',
            field=django.contrib.postgres.fields.ranges.IntegerRangeField(default=NumericRange(2, 30), verbose_name='number of people'),
        ),
        migrations.RunSQL('commit;'),
        migrations.RunSQL('update material_activity set num_people = int4range(min_people, max_people);'),
        migrations.RunSQL('commit;'),
        migrations.RemoveField(
            model_name='activity',
            name='max_people',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='min_people',
        ),
    ]
