# Generated by Django 2.2.6 on 2019-10-27 09:46

from django.db import migrations
import localized_fields.fields.char_field
import localized_fields.fields.text_field


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0005_auto_20190105_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='notes',
            field=localized_fields.fields.text_field.LocalizedTextField(blank=True, null=True, required=[], verbose_name='notes'),
        ),
        migrations.AlterField(
            model_name='groupfeature',
            name='name',
            field=localized_fields.fields.char_field.LocalizedCharField(max_length=512, required=[], verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=localized_fields.fields.char_field.LocalizedCharField(max_length=512, required=[], verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='material',
            name='brief',
            field=localized_fields.fields.text_field.LocalizedTextField(required=[], verbose_name='brief'),
        ),
        migrations.AlterField(
            model_name='material',
            name='goal',
            field=localized_fields.fields.text_field.LocalizedTextField(blank=True, null=True, required=[], verbose_name='goal'),
        ),
        migrations.AlterField(
            model_name='material',
            name='title',
            field=localized_fields.fields.char_field.LocalizedCharField(max_length=512, required=[], verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=localized_fields.fields.char_field.LocalizedCharField(max_length=512, required=[], verbose_name='name'),
        ),
    ]
