# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 09:40
from __future__ import unicode_literals

from datetime import timedelta

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0005_auto_20170709_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='duration',
            field=models.DurationField(blank=True, null=True, verbose_name='duration'),
        ),
        migrations.AlterField(
            model_name='video',
            name='duration',
            field=models.DurationField(default=timedelta(minutes=1), verbose_name='duration'),
            preserve_default=False,
        ),
    ]
