# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0005_auto_20170504_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='attachment',
            field=models.FileField(blank=True, upload_to='material/attachments', verbose_name='attachment'),
        ),
        migrations.AddField(
            model_name='reading',
            name='attachment',
            field=models.FileField(blank=True, upload_to='material/attachments', verbose_name='attachment'),
        ),
        migrations.AddField(
            model_name='video',
            name='attachment',
            field=models.FileField(blank=True, upload_to='material/attachments', verbose_name='attachment'),
        ),
    ]
