# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0006_auto_20170504_2247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='num_people',
        ),
        migrations.AddField(
            model_name='activity',
            name='max_people',
            field=models.PositiveSmallIntegerField(default=30, verbose_name='maximum number of people'),
        ),
        migrations.AddField(
            model_name='activity',
            name='min_people',
            field=models.PositiveSmallIntegerField(default=2, verbose_name='minimum number of people'),
        ),
    ]
