# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 09:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0006_auto_20170710_1140'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Activity', 'verbose_name_plural': 'Activities'},
        ),
        migrations.AlterModelOptions(
            name='approval',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Approval', 'verbose_name_plural': 'Approvals'},
        ),
        migrations.AlterModelOptions(
            name='link',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Link', 'verbose_name_plural': 'Links'},
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Material', 'verbose_name_plural': 'Materials'},
        ),
        migrations.AlterModelOptions(
            name='reading',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Reading', 'verbose_name_plural': 'Readings'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Video', 'verbose_name_plural': 'Videos'},
        ),
        migrations.RemoveField(
            model_name='approval',
            name='requested',
        ),
        migrations.AddField(
            model_name='approval',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='creation timestamp'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='material',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='creation timestamp'),
            preserve_default=False,
        ),
    ]
