# Generated by Django 2.2.7 on 2019-11-24 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0006_auto_20191027_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='highlight',
            field=models.BooleanField(default=False, verbose_name='highlighted on search'),
        ),
    ]
