# Generated by Django 2.2.7 on 2019-11-24 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0007_material_highlight'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ['-highlight', '-timestamp'], 'verbose_name': 'Material', 'verbose_name_plural': 'Materials'},
        ),
        migrations.AddField(
            model_name='reading',
            name='attachment',
            field=models.FileField(blank=True, upload_to='material/activities/', verbose_name='attachment'),
        ),
    ]
