# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-18 10:41
from __future__ import unicode_literals

from django.db import migrations
import localized_fields.fields.char_field
import localized_fields.fields.uniqueslug_field
import tk.material.fields


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0007_auto_20170710_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='name',
            field=localized_fields.fields.char_field.LocalizedCharField(max_length=512, required=['eu'], uniqueness=[], verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='groupfeature',
            name='name',
            field=localized_fields.fields.char_field.LocalizedCharField(max_length=512, required=['eu'], uniqueness=[], verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=localized_fields.fields.char_field.LocalizedCharField(max_length=512, required=['eu'], uniqueness=[], verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='material',
            name='brief',
            field=tk.material.fields.LocalizedMarkdownxTextField(required=[], uniqueness=[], verbose_name='brief'),
        ),
        migrations.AlterField(
            model_name='material',
            name='slug',
            field=localized_fields.fields.uniqueslug_field.LocalizedUniqueSlugField(include_time=False, populate_from='title', required=['eu'], uniqueness=['eu', 'es']),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=localized_fields.fields.char_field.LocalizedCharField(max_length=512, required=['eu'], uniqueness=[], verbose_name='name'),
        ),
    ]
