# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0007_auto_20170504_2250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='id',
        ),
        migrations.AddField(
            model_name='language',
            name='code',
            field=models.CharField(default='', max_length=16, primary_key=True, serialize=False, verbose_name='code'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activity',
            name='link',
            field=models.URLField(blank=True, help_text='Link the material if its copyright does not allow sharing it.', verbose_name='link'),
        ),
        migrations.AlterField(
            model_name='reading',
            name='link',
            field=models.URLField(blank=True, help_text='Link the material if its copyright does not allow sharing it.', verbose_name='link'),
        ),
        migrations.AlterField(
            model_name='video',
            name='link',
            field=models.URLField(blank=True, help_text='Link the material if its copyright does not allow sharing it.', verbose_name='link'),
        ),
    ]
