# Generated by Django 2.0 on 2018-05-21 17:16

from django.db import migrations, models
import tk.material.fields


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0008_auto_20170718_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='goals',
        ),
        migrations.RemoveField(
            model_name='material',
            name='subject',
        ),
        migrations.AddField(
            model_name='material',
            name='goal',
            field=tk.material.fields.LocalizedMarkdownxTextField(blank=True, null=True, required=[], uniqueness=[], verbose_name='goal'),
        ),
        migrations.AddField(
            model_name='material',
            name='subjects',
            field=models.ManyToManyField(to='material.Subject', verbose_name='subject'),
        ),
        migrations.DeleteModel(
            name='Goal',
        ),
    ]
