# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0008_auto_20170505_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='comment',
            field=models.TextField(blank=True, default='', verbose_name='comment'),
            preserve_default=False,
        ),
    ]
