# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 12:17
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0009_auto_20170508_1411'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512, verbose_name='title')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True)),
                ('brief', models.TextField(blank=True, verbose_name='brief')),
                ('author', models.CharField(blank=True, max_length=512, verbose_name='author')),
                ('link', models.URLField(verbose_name='link')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material.Subject', verbose_name='subject')),
            ],
            options={
                'verbose_name': 'Link',
                'verbose_name_plural': 'Links',
            },
        ),
        migrations.AlterModelOptions(
            name='reading',
            options={'verbose_name': 'Reading', 'verbose_name_plural': 'Readings'},
        ),
        migrations.AlterField(
            model_name='activity',
            name='attachment',
            field=models.FileField(blank=True, upload_to='material/activities/', verbose_name='attachment'),
        ),
        migrations.AlterField(
            model_name='reading',
            name='attachment',
            field=models.FileField(blank=True, upload_to='material/readings/', verbose_name='attachment'),
        ),
        migrations.AlterField(
            model_name='video',
            name='attachment',
            field=models.FileField(blank=True, upload_to='material/videos', verbose_name='attachment'),
        ),
    ]
