# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0010_auto_20170508_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='brief_es',
            field=models.TextField(blank=True, null=True, verbose_name='brief'),
        ),
        migrations.AddField(
            model_name='activity',
            name='brief_eu',
            field=models.TextField(blank=True, null=True, verbose_name='brief'),
        ),
        migrations.AddField(
            model_name='activity',
            name='notes_es',
            field=models.TextField(blank=True, null=True, verbose_name='notes'),
        ),
        migrations.AddField(
            model_name='activity',
            name='notes_eu',
            field=models.TextField(blank=True, null=True, verbose_name='notes'),
        ),
        migrations.AddField(
            model_name='activity',
            name='title_es',
            field=models.CharField(max_length=512, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='activity',
            name='title_eu',
            field=models.CharField(max_length=512, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='goal',
            name='name_es',
            field=models.CharField(max_length=512, null=True, verbose_name='izena'),
        ),
        migrations.AddField(
            model_name='goal',
            name='name_eu',
            field=models.CharField(max_length=512, null=True, verbose_name='izena'),
        ),
        migrations.AddField(
            model_name='groupfeature',
            name='name_es',
            field=models.CharField(max_length=512, null=True, verbose_name='izena'),
        ),
        migrations.AddField(
            model_name='groupfeature',
            name='name_eu',
            field=models.CharField(max_length=512, null=True, verbose_name='izena'),
        ),
        migrations.AddField(
            model_name='language',
            name='name_es',
            field=models.CharField(max_length=512, null=True, verbose_name='izena'),
        ),
        migrations.AddField(
            model_name='language',
            name='name_eu',
            field=models.CharField(max_length=512, null=True, verbose_name='izena'),
        ),
        migrations.AddField(
            model_name='link',
            name='brief_es',
            field=models.TextField(blank=True, null=True, verbose_name='brief'),
        ),
        migrations.AddField(
            model_name='link',
            name='brief_eu',
            field=models.TextField(blank=True, null=True, verbose_name='brief'),
        ),
        migrations.AddField(
            model_name='link',
            name='title_es',
            field=models.CharField(max_length=512, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='link',
            name='title_eu',
            field=models.CharField(max_length=512, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='location',
            name='name_es',
            field=models.CharField(max_length=512, null=True, verbose_name='izena'),
        ),
        migrations.AddField(
            model_name='location',
            name='name_eu',
            field=models.CharField(max_length=512, null=True, verbose_name='izena'),
        ),
        migrations.AddField(
            model_name='reading',
            name='brief_es',
            field=models.TextField(blank=True, null=True, verbose_name='brief'),
        ),
        migrations.AddField(
            model_name='reading',
            name='brief_eu',
            field=models.TextField(blank=True, null=True, verbose_name='brief'),
        ),
        migrations.AddField(
            model_name='reading',
            name='title_es',
            field=models.CharField(max_length=512, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='reading',
            name='title_eu',
            field=models.CharField(max_length=512, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='subject',
            name='name_es',
            field=models.CharField(max_length=512, null=True, verbose_name='izena'),
        ),
        migrations.AddField(
            model_name='subject',
            name='name_eu',
            field=models.CharField(max_length=512, null=True, verbose_name='izena'),
        ),
        migrations.AddField(
            model_name='video',
            name='brief_es',
            field=models.TextField(blank=True, null=True, verbose_name='brief'),
        ),
        migrations.AddField(
            model_name='video',
            name='brief_eu',
            field=models.TextField(blank=True, null=True, verbose_name='brief'),
        ),
        migrations.AddField(
            model_name='video',
            name='title_es',
            field=models.CharField(max_length=512, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='video',
            name='title_eu',
            field=models.CharField(max_length=512, null=True, verbose_name='title'),
        ),
    ]
