# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 12:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0011_auto_20170509_1100'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='activity',
            name='group_feature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='material.GroupFeature', verbose_name='group feature'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='material.Location', verbose_name='location'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='material.Subject', verbose_name='subject'),
        ),
        migrations.AlterField(
            model_name='link',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='material.Subject', verbose_name='subject'),
        ),
        migrations.AlterField(
            model_name='reading',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='material.Language', verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='reading',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='material.Subject', verbose_name='subject'),
        ),
        migrations.AlterField(
            model_name='video',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='material.Subject', verbose_name='subject'),
        ),
        migrations.AlterUniqueTogether(
            name='approval',
            unique_together=set([]),
        ),
        migrations.AddField(
            model_name='approvalresource',
            name='activity',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='material.Activity'),
        ),
        migrations.AddField(
            model_name='approvalresource',
            name='link',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='material.Link'),
        ),
        migrations.AddField(
            model_name='approvalresource',
            name='reading',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='material.Reading'),
        ),
        migrations.AddField(
            model_name='approvalresource',
            name='video',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='material.Video'),
        ),
        migrations.RemoveField(
            model_name='approval',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='approval',
            name='object_id',
        ),
        migrations.AddField(
            model_name='approval',
            name='resource',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='material.ApprovalResource', verbose_name='resource'),
            preserve_default=False,
        ),
    ]
