# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 14:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0012_auto_20170510_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approvalresource',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='approvalresource',
            name='link',
        ),
        migrations.RemoveField(
            model_name='approvalresource',
            name='reading',
        ),
        migrations.RemoveField(
            model_name='approvalresource',
            name='video',
        ),
        migrations.RemoveField(
            model_name='approval',
            name='resource',
        ),
        migrations.AddField(
            model_name='approval',
            name='activity',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='material.Activity'),
        ),
        migrations.AddField(
            model_name='approval',
            name='link',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='material.Link'),
        ),
        migrations.AddField(
            model_name='approval',
            name='reading',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='material.Reading'),
        ),
        migrations.AddField(
            model_name='approval',
            name='video',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='material.Video'),
        ),
        migrations.DeleteModel(
            name='ApprovalResource',
        ),
    ]
