# Generated by Django 2.2.7 on 2019-12-29 22:12
import os

from django.db import migrations, models
import localized_fields.fields.text_field

DIR = os.path.dirname(os.path.realpath(__file__))
WELCOME = os.path.join(DIR, 'welcome_message.html')

def create_welcome(apps, schema_editor):
    with open(WELCOME, 'r') as f:
        content = f.read()
    db = schema_editor.connection.alias
    Chunk = apps.get_model('chunks', 'Chunk')
    Chunk.objects.using(db).create(
        slug="welcome",
        content=content,
    )

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('content', localized_fields.fields.text_field.LocalizedTextField(required=[], verbose_name='content')),
            ],
            options={
                'verbose_name': 'Chunk',
                'verbose_name_plural': 'Chunks',
                'ordering': ['slug'],
            },
        ),
        migrations.RunPython(create_welcome),
    ]
